# install Apache2 using Ansible
- name: Setup nginx server on myserver list (host group)
  hosts: myservers
  become: True
  vars:
    base_path: /vagrant/Ansible-inventories
    apache2_version: 2.4.41
  tasks:
    # first task --- instal apache2
    - name: Install the latest version of nginx
      command: apt install apache2 -y
      # -y installs without a prompt

    # second task --- start the service
    - name: Start apache2
      service:
        name: apache2
        enabled: yes
        state: started

    # third task --- confirm apache2 version
    - name: Get nginx installed version
      command: apache2 -v
      register: apache2_version
    # print the current version of apache2 on screen
    - name: print apache2 version
      debug:
        msg: "The current version of apache2 is {{apache2_version}}"

    # forth task --- connfirm status
    - name: Getthe status of apache2 service
      command: systemctl status apache2

    # fifth task --- copy file to remote server
    - name: Ansible copy file to remote server
      copy:
        src: "{{base_path}}/test.yml"
        dest: /home/vagrant
